version: '3.7'

services:
  unbound-family:
    container_name: unbound-family
    image: "ghcr.io/bebasid/unbound:master"
    expose:
      - "53"
    networks:
      vpcbr:
        ipv4_address: 172.27.154.20
    ports:
      - target: 53
        published: 32053
        protocol: tcp
        mode: host
      - target: 53
        published: 32053
        protocol: udp
        mode: host
    restart: unless-stopped

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.154.0/24


volumes:
  mydata: